make cards
Daryyya/test pull request #3
Opened 2022-06-26 06:51 UTC by Daryyya

2022-06-27 13:14 UTC, U256 requested changes

2022-06-27 13:14 UTC, U256 commented on css/_content-block.scss
> +	.card-text {
и тут, и везде

2022-06-27 13:14 UTC, U256 commented on css/style.css
>    display: none;
Добавь css в gitignore!

2022-06-27 13:14 UTC, U256 commented on css/style.scss
>  $background-color: #ff7400;
Пробел перед этой строкой. Между принципиально разными значениями в коде стоит ставить пробелы

2022-06-27 13:14 UTC, U256 commented on img/Mask Group.svg
> +<svg width="87" height="87" viewBox="0 0 87 87" fill="none" xmlns="http://www.w3.org/2000/svg">
Приведи в порядок все свои изображения. Они должны называться кебаб-кейсом, всё с маленькой буквы

2022-06-27 13:14 UTC, U256 commented on index.html
>  </html>
Добавь пустую строку в конце файла. Это стандарт для всех документов

2022-06-28 06:52 UTC, Daryyya commented on css/_content-block.scss
> +	.card-title {
++

2022-06-28 06:52 UTC, Daryyya commented on css/_content-block.scss
> +	.card-text {
++

2022-06-28 06:53 UTC, Daryyya commented on css/style.scss
>  $background-color: #ff7400;
++

2022-06-28 06:53 UTC, Daryyya commented on index.html
>  </html>
++

2022-06-28 06:57 UTC, Daryyya commented on img/Mask Group.svg
> +<svg width="87" height="87" viewBox="0 0 87 87" fill="none" xmlns="http://www.w3.org/2000/svg">
++

2022-06-28 07:04 UTC, Daryyya commented on css/style.css
>    display: none;
++

2022-06-28 10:54 UTC, U256 commented on .gitignore
> +.css
Нужна пустая строка в конце документа. И нужно указать путь и папку

2022-06-28 14:00 UTC, merged